version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    command: ['start', '--hostname-strict', 'false']
    links:
      - postgres
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=Password
      - DB_PASSWORD=KeyCloak
      - DB_USER=keycloak
      - DB_DATABASE=keycloak
      - DB_VENDOR=mysql
      - DB_ADDR=mariadb
      - PROXY_ADDRESS_FORWARDING=true
      - KC_HTTPS_KEY_STORE_PASSWORD=password
      - KC_HTTPS_KEY_STORE_FILE=/opt/keycloak/conf/keycloak.keystore
    volumes:
      - ./keycloak.keystore:/opt/keycloak/conf/keycloak.keystore
    depends_on:
      - mariadb
    restart: always
    ports:
      - 8443:8443
      - 8080:8080
    networks:
      - default

  mariadb:
    image: mariadb:10
    volumes:
      - ./mariadb-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: keycloak
      MARIADB_USER: keycloak
      MARIADB_PASSWORD: KeyCloak
    ports:
      - 13306:3306
    restart: always
    networks:
      - default
