version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    command: ['start']
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=Password
      - KC_DB=postgres
      # Replace me!
      - KC_DB_URL_HOST=my.database.server.net
      - KC_DB_SCHEMA=public
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_URL_PORT=5432
      - KC_DB_PASSWORD=KeyCloak
      - KC_DB_USERNAME=keycloak
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - PROXY_ADDRESS_FORWARDING=true
      - KC_CACHE_CONFIG_FILE=cache-ispn-jdbc-ping.xml
      - KC_HTTPS_KEY_STORE_PASSWORD=password
      - KC_HTTPS_KEY_STORE_FILE=/opt/keycloak/conf/keycloak.keystore
      - JGROUPS_DISCOVERY_EXTERNAL_IP=${MYIP}
    volumes:
      - ./cache-ispn-jdbc-ping.xml:/opt/keycloak/conf/cache-ispn-jdbc-ping.xml:ro
      - ./keycloak.keystore:/opt/keycloak/conf/keycloak.keystore
    restart: always
    ports:
      - 18443:8443
      - 18080:8080
      - 7800:7800
    networks:
      - default
