version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    command: ['start', '--hostname-strict', 'false']
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=Password
      - KC_DB=postgres
      - KC_DB_PASSWORD=KeyCloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_URL="'jdbc:postgresql://kctestdb.pfpk.pro/keycloak"
      - PROXY_ADDRESS_FORWARDING=true
      - KC_HTTPS_KEY_STORE_PASSWORD=password
      - KC_HTTPS_KEY_STORE_FILE=/opt/keycloak/conf/keycloak.keystore
      - KC_CACHE_STACK=kubernetes
      - JAVA_OPTS_APPEND="-Djgroups.dns.query=kctest.pfpk.pro"
    volumes:
      - ./keycloak.keystore:/opt/keycloak/conf/keycloak.keystore
    restart: always
    ports:
      - 18443:8443
      - 18080:8080
    networks:
      - default
